<a href="https://colab.research.google.com/github/SriRamK345/Pandas_lib/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas
* Data Analysis and data manipulation
* Reshaping of Datasets
* Converting other data structure into Dataframe
* Time series
* Collect and Transform data

In [1]:
import pandas as pd

In [2]:
pd.Series([10,20,30,40,66,55,44,33,23]) # panda series using List

0    10
1    20
2    30
3    40
4    66
5    55
6    44
7    33
8    23
dtype: int64

In [3]:
list_data = [10,20,30,40,66,55,44,33,23]
list_index = ['a','b','c','d','e','f','g','h','r']

In [4]:
Comb=pd.Series(list_data,list_index) # (data , Index , dtype)
Comb

a    10
b    20
c    30
d    40
e    66
f    55
g    44
h    33
r    23
dtype: int64

In [5]:
type(Comb)

pandas.core.series.Series

In [6]:
dist = {'AA':10,'BB':20,'CC':30,'DD':40} # pandas series using Dictionary

In [7]:
pd.Series(dist)

AA    10
BB    20
CC    30
DD    40
dtype: int64

In [8]:
Comb.size

9

In [9]:
Comb.shape

(9,)

In [10]:
Comb.ndim # dimention of the array

1

In [11]:
Comb.values

array([10, 20, 30, 40, 66, 55, 44, 33, 23])

In [12]:
# Diff mentiods in pandas series
variable = pd.Series([10,20,30,40,66,55,44,33,23],index=['a','b','v','d','g','f','s','h','r'])
variable

a    10
b    20
v    30
d    40
g    66
f    55
s    44
h    33
r    23
dtype: int64

In [13]:
variable.items()

In [14]:
list(variable.items())

[('a', 10),
 ('b', 20),
 ('v', 30),
 ('d', 40),
 ('g', 66),
 ('f', 55),
 ('s', 44),
 ('h', 33),
 ('r', 23)]

In [15]:
for index,value in variable.items():
  print(index,"--", value)

a -- 10
b -- 20
v -- 30
d -- 40
g -- 66
f -- 55
s -- 44
h -- 33
r -- 23


In [16]:
variable.keys()

Index(['a', 'b', 'v', 'd', 'g', 'f', 's', 'h', 'r'], dtype='object')

In [17]:
variable.values

array([10, 20, 30, 40, 66, 55, 44, 33, 23])

In [18]:
[i for i in variable.values] # list comprehension

[10, 20, 30, 40, 66, 55, 44, 33, 23]

In [19]:
variable.index

Index(['a', 'b', 'v', 'd', 'g', 'f', 's', 'h', 'r'], dtype='object')

In [20]:
[i for i in variable.index] # list comprehension

['a', 'b', 'v', 'd', 'g', 'f', 's', 'h', 'r']

In [21]:
variable.isin([10,20,33])

a     True
b     True
v    False
d    False
g    False
f    False
s    False
h     True
r    False
dtype: bool

In [22]:
variable[variable.isin([10,20,33])]

a    10
b    20
h    33
dtype: int64

In [23]:
variable[variable>30]

d    40
g    66
f    55
s    44
h    33
dtype: int64

In [24]:
variable["d":"s"] # slicing

d    40
g    66
f    55
s    44
dtype: int64

In [25]:
variable[["d","s"]] # Indexing

d    40
s    44
dtype: int64

Create dataframe using Numpy array

In [26]:
import numpy as np

In [27]:
Dummy = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
Dummy

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
pd.DataFrame(Dummy) # Create dataframe using Numpy array

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [29]:
df = pd.DataFrame(Dummy,index=['a','b','c','d'],columns=['AA','BB','CC']) # Create dataframe using Numpy array
df

AA  BB  CC
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [30]:
df.head() # first 5 rows

AA  BB  CC
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [31]:
df.tail() # last 5 rows

AA  BB  CC
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [32]:
df.columns

Index(['AA', 'BB', 'CC'], dtype='object')

In [33]:
df.columns = ['A','B','C'] # change column name
df

A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [34]:
np.random.seed(101) # set seed
d_f=pd.DataFrame(np.random.randn(6,6)) # random number
d_f

0         1         2         3         4         5
0  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
1 -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
2  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
3  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119
4 -0.134841  0.390528  0.166905  0.184502  0.807706  0.072960
5  0.638787  0.329646 -0.497104 -0.754070 -0.943406  0.484752

In [35]:
d_f.columns = ['A','B','C','D','E','F'] # change column name
d_f.index = ['a','b','c','d','e','f'] # change index name
d_f

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119
e -0.134841  0.390528  0.166905  0.184502  0.807706  0.072960
f  0.638787  0.329646 -0.497104 -0.754070 -0.943406  0.484752

In [36]:
d_f['A']

a    2.706850
b   -0.848077
c    0.188695
d    2.605967
e   -0.134841
f    0.638787
Name: A, dtype: float64

In [37]:
d_f[['A']]

A
a  2.706850
b -0.848077
c  0.188695
d  2.605967
e -0.134841
f  0.638787

In [38]:
d_f[['A','B']]['b':'d']

A         B
b -0.848077  0.605965
c  0.188695 -0.758872
d  2.605967  0.683509

In [39]:
#d_f['a']

In [40]:
d_f['a':'a']

A         B         C         D         E         F
a  2.70685  0.628133  0.907969  0.503826  0.651118 -0.319318

#loc and iloc

In [41]:
d_f

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119
e -0.134841  0.390528  0.166905  0.184502  0.807706  0.072960
f  0.638787  0.329646 -0.497104 -0.754070 -0.943406  0.484752

In [42]:
d_f.loc['a':'d'] # loc is label based

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119

In [43]:
d_f.iloc[0:4] # iloc is index based

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119

In [44]:
np.random.seed(101)
df2 = pd.DataFrame(np.random.randint(10,50,(7,7)), columns = ['A','B','C','D','E','F','G'],index = ['a','b','c','d','e','f','g'])
df2

A   B   C   D   E   F   G
a  41  21  27  16  33  21  19
b  23  14  38  10  15  22  39
c  29  18  39  44  18  29  20
d  22  41  33  10  19  18  46
e  29  45  38  17  20  49  48
f  19  28  17  49  25  10  22
g  27  21  25  43  39  34  46

In [45]:
df2>20

A      B      C      D      E      F      G
a   True   True   True  False   True   True  False
b   True  False   True  False  False   True   True
c   True  False   True   True  False   True  False
d   True   True   True  False  False  False   True
e   True   True   True  False  False   True   True
f  False   True  False   True   True  False   True
g   True   True   True   True   True   True   True

In [46]:
df2[df2>20]

A     B     C     D     E     F     G
a  41.0  21.0  27.0   NaN  33.0  21.0   NaN
b  23.0   NaN  38.0   NaN   NaN  22.0  39.0
c  29.0   NaN  39.0  44.0   NaN  29.0   NaN
d  22.0  41.0  33.0   NaN   NaN   NaN  46.0
e  29.0  45.0  38.0   NaN   NaN  49.0  48.0
f   NaN  28.0   NaN  49.0  25.0   NaN  22.0
g  27.0  21.0  25.0  43.0  39.0  34.0  46.0

In [47]:
 df2[(df2['A']>20) & (df2['B']>30)]

A   B   C   D   E   F   G
d  22  41  33  10  19  18  46
e  29  45  38  17  20  49  48

In [48]:
# add column df
df2

A   B   C   D   E   F   G
a  41  21  27  16  33  21  19
b  23  14  38  10  15  22  39
c  29  18  39  44  18  29  20
d  22  41  33  10  19  18  46
e  29  45  38  17  20  49  48
f  19  28  17  49  25  10  22
g  27  21  25  43  39  34  46

In [49]:
df2['H'] = df2['A']+df2['B']
df2

A   B   C   D   E   F   G   H
a  41  21  27  16  33  21  19  62
b  23  14  38  10  15  22  39  37
c  29  18  39  44  18  29  20  47
d  22  41  33  10  19  18  46  63
e  29  45  38  17  20  49  48  74
f  19  28  17  49  25  10  22  47
g  27  21  25  43  39  34  46  48

In [50]:
# remove column
df2.drop('H',axis=1,inplace=True)
df2

A   B   C   D   E   F   G
a  41  21  27  16  33  21  19
b  23  14  38  10  15  22  39
c  29  18  39  44  18  29  20
d  22  41  33  10  19  18  46
e  29  45  38  17  20  49  48
f  19  28  17  49  25  10  22
g  27  21  25  43  39  34  46

In [51]:
# drop row
df2.drop('a',axis=0,inplace=True)
df2

A   B   C   D   E   F   G
b  23  14  38  10  15  22  39
c  29  18  39  44  18  29  20
d  22  41  33  10  19  18  46
e  29  45  38  17  20  49  48
f  19  28  17  49  25  10  22
g  27  21  25  43  39  34  46

In [52]:
import pandas as pd
import numpy as np

df3 = pd.DataFrame({
    'A': [1, np.nan, 3,4,5,np.nan],
    'B': [4, 5, np.nan, 7, 8, 9],
    'C': [10, 11, 12, 13, 14, 15]
})

df3

A    B   C
0  1.0  4.0  10
1  NaN  5.0  11
2  3.0  NaN  12
3  4.0  7.0  13
4  5.0  8.0  14
5  NaN  9.0  15

In [53]:
df3.isnull().sum()

A    2
B    1
C    0
dtype: int64

In [54]:
len(df3)

6

In [55]:
# percentage of null values
df3.isnull().sum()/len(df3)*100

A    33.333333
B    16.666667
C     0.000000
dtype: float64

In [56]:
df3.notnull().sum()

A    4
B    5
C    6
dtype: int64

In [57]:
df3.isnull().sum().sum() #

3

In [58]:
df3.isnull().any()

A     True
B     True
C    False
dtype: bool

In [59]:
df3.isnull().any(axis=1)

0    False
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [60]:
# drop null values
df3.dropna()

A    B   C
0  1.0  4.0  10
3  4.0  7.0  13
4  5.0  8.0  14

In [61]:
df3

A    B   C
0  1.0  4.0  10
1  NaN  5.0  11
2  3.0  NaN  12
3  4.0  7.0  13
4  5.0  8.0  14
5  NaN  9.0  15

In [62]:
df3.dropna(axis=1,how='all') # how = any or all

A    B   C
0  1.0  4.0  10
1  NaN  5.0  11
2  3.0  NaN  12
3  4.0  7.0  13
4  5.0  8.0  14
5  NaN  9.0  15

In [63]:
# fill null values
df3.fillna(233)

A      B   C
0    1.0    4.0  10
1  233.0    5.0  11
2    3.0  233.0  12
3    4.0    7.0  13
4    5.0    8.0  14
5  233.0    9.0  15

In [64]:
df3.fillna(df3.mean())

A    B   C
0  1.00  4.0  10
1  3.25  5.0  11
2  3.00  6.6  12
3  4.00  7.0  13
4  5.00  8.0  14
5  3.25  9.0  15

In [65]:
df3.fillna(df3.mean()['A'])

A     B   C
0  1.00  4.00  10
1  3.25  5.00  11
2  3.00  3.25  12
3  4.00  7.00  13
4  5.00  8.00  14
5  3.25  9.00  15

In [66]:
  df3.fillna(method='ffill') # ffill 0r bfill

A    B   C
0  1.0  4.0  10
1  1.0  5.0  11
2  3.0  5.0  12
3  4.0  7.0  13
4  5.0  8.0  14
5  5.0  9.0  15

In [67]:
df3['A'].fillna(df3['A'].mean())

0    1.00
1    3.25
2    3.00
3    4.00
4    5.00
5    3.25
Name: A, dtype: float64

In [68]:
df3.reset_index(drop=True,inplace=True)
df3

A    B   C
0  1.0  4.0  10
1  NaN  5.0  11
2  3.0  NaN  12
3  4.0  7.0  13
4  5.0  8.0  14
5  NaN  9.0  15

In [69]:
new_ind = 'CA NY WY OR CO EE'.split()
new_ind

['CA', 'NY', 'WY', 'OR', 'CO', 'EE']

In [70]:
df3["new_index"]= new_ind

In [71]:
df3

A    B   C new_index
0  1.0  4.0  10        CA
1  NaN  5.0  11        NY
2  3.0  NaN  12        WY
3  4.0  7.0  13        OR
4  5.0  8.0  14        CO
5  NaN  9.0  15        EE

In [72]:
df3.set_index('new_index',inplace=True)
df3

A    B   C
new_index              
CA         1.0  4.0  10
NY         NaN  5.0  11
WY         3.0  NaN  12
OR         4.0  7.0  13
CO         5.0  8.0  14
EE         NaN  9.0  15

In [75]:
# multi index

arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [83]:
# concatenation

dff1 = pd.DataFrame(np.random.randint(1,12,(3,4)),columns=['A','B','C','D'])
dff1
dff2 = pd.DataFrame(np.random.randint(1,12,(3,4)),columns=['A','B','C','D'])
dff2

A  B   C  D
0  5  7  10  5
1  4  2   5  5
2  5  3   4  2

In [84]:
pd.concat([dff1,dff2])

A  B   C  D
0  8  5   2  9
1  5  1   5  3
2  6  9   2  9
0  5  7  10  5
1  4  2   5  5
2  5  3   4  2

In [85]:
pd.concat([dff1,dff2],axis=1)

A  B  C  D  A  B   C  D
0  8  5  2  9  5  7  10  5
1  5  1  5  3  4  2   5  5
2  6  9  2  9  5  3   4  2

In [86]:
pd.concat([dff1,dff2],axis=1,join='inner')

A  B  C  D  A  B   C  D
0  8  5  2  9  5  7  10  5
1  5  1  5  3  4  2   5  5
2  6  9  2  9  5  3   4  2

In [89]:
pd.concat([dff1,dff2],ignore_index= True) # to order the indez no

A  B   C  D
0  8  5   2  9
1  5  1   5  3
2  6  9   2  9
3  5  7  10  5
4  4  2   5  5
5  5  3   4  2

In [103]:
# merge the dataFrame

ddf1 = pd.DataFrame({
    'name': ['Alex', 'Amy', 'naman', 'kishore'],
    'subject_id': ['sub1', 'sub2', 'sub3', 'sub4'],
    'marks': [99, 92,34,55]})

ddf1

name subject_id  marks
0     Alex       sub1     99
1      Amy       sub2     92
2    naman       sub3     34
3  kishore       sub4     55

In [104]:
ddf2 = pd.DataFrame({
    'name': [ 'kishore','Alex' , 'Amy', 'naman'],
    'class': ['class1', 'class2', 'class3', 'class4']
    })

ddf2


name   class
0  kishore  class1
1     Alex  class2
2      Amy  class3
3    naman  class4

In [107]:
merged = pd.merge(ddf1,ddf2,on='name',how = 'outer') # inner,left,right,outer
merged

name subject_id  marks   class
0     Alex       sub1     99  class2
1      Amy       sub2     92  class3
2    naman       sub3     34  class4
3  kishore       sub4     55  class1