<a href="https://colab.research.google.com/github/SriRamK345/Pandas_lib/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas
* Data Analysis and data manipulation
* Reshaping of Datasets
* Converting other data structure into Dataframe
* Time series
* Collect and Transform data

In [239]:
import pandas as pd

In [240]:
pd.Series([10,20,30,40,66,55,44,33,23]) # panda series using List

0    10
1    20
2    30
3    40
4    66
5    55
6    44
7    33
8    23
dtype: int64

In [241]:
list_data = [10,20,30,40,66,55,44,33,23]
list_index = ['a','b','c','d','e','f','g','h','r']

In [242]:
Comb=pd.Series(list_data,list_index) # (data , Index , dtype)
Comb

a    10
b    20
c    30
d    40
e    66
f    55
g    44
h    33
r    23
dtype: int64

In [243]:
type(Comb)

pandas.core.series.Series

In [244]:
dist = {'AA':10,'BB':20,'CC':30,'DD':40} # pandas series using Dictionary

In [245]:
pd.Series(dist)

AA    10
BB    20
CC    30
DD    40
dtype: int64

In [246]:
Comb.size

9

In [247]:
Comb.shape

(9,)

In [248]:
Comb.ndim # dimention of the array

1

In [249]:
Comb.values

array([10, 20, 30, 40, 66, 55, 44, 33, 23])

In [250]:
# Diff mentiods in pandas series
variable = pd.Series([10,20,30,40,66,55,44,33,23],index=['a','b','v','d','g','f','s','h','r'])
variable

a    10
b    20
v    30
d    40
g    66
f    55
s    44
h    33
r    23
dtype: int64

In [251]:
variable.items()

In [252]:
list(varible.items())

[('a', 10),
 ('b', 20),
 ('v', 30),
 ('d', 40),
 ('g', 66),
 ('f', 55),
 ('s', 44),
 ('h', 33),
 ('r', 23)]

In [253]:
for index,value in varible.items():
  print(index,"--", value)

a -- 10
b -- 20
v -- 30
d -- 40
g -- 66
f -- 55
s -- 44
h -- 33
r -- 23


In [254]:
variable.keys()

Index(['a', 'b', 'v', 'd', 'g', 'f', 's', 'h', 'r'], dtype='object')

In [255]:
variable.values

array([10, 20, 30, 40, 66, 55, 44, 33, 23])

In [256]:
[i for i in variable.values] # list comprehension

[10, 20, 30, 40, 66, 55, 44, 33, 23]

In [257]:
variable.index

Index(['a', 'b', 'v', 'd', 'g', 'f', 's', 'h', 'r'], dtype='object')

In [258]:
[i for i in variable.index] # list comprehension

['a', 'b', 'v', 'd', 'g', 'f', 's', 'h', 'r']

In [259]:
variable.isin([10,20,33])

a     True
b     True
v    False
d    False
g    False
f    False
s    False
h     True
r    False
dtype: bool

In [260]:
variable[variable.isin([10,20,33])]

a    10
b    20
h    33
dtype: int64

In [261]:
variable[variable>30]

d    40
g    66
f    55
s    44
h    33
dtype: int64

In [262]:
variable["d":"s"] # slicing

d    40
g    66
f    55
s    44
dtype: int64

In [263]:
variable[["d","s"]] # Indexing

d    40
s    44
dtype: int64

Create dataframe using Numpy array

In [264]:
import numpy as np

In [265]:
Dummy = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
Dummy

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [266]:
pd.DataFrame(Dummy) # Create dataframe using Numpy array

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [267]:
df = pd.DataFrame(Dummy,index=['a','b','c','d'],columns=['AA','BB','CC']) # Create dataframe using Numpy array
df

AA  BB  CC
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [268]:
df.head() # first 5 rows

AA  BB  CC
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [269]:
df.tail() # last 5 rows

AA  BB  CC
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [270]:
df.columns

Index(['AA', 'BB', 'CC'], dtype='object')

In [271]:
df.columns = ['A','B','C'] # change column name
df

A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [272]:
np.random.seed(101) # set seed
d_f=pd.DataFrame(np.random.randn(6,6)) # random number
d_f

0         1         2         3         4         5
0  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
1 -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
2  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
3  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119
4 -0.134841  0.390528  0.166905  0.184502  0.807706  0.072960
5  0.638787  0.329646 -0.497104 -0.754070 -0.943406  0.484752

In [273]:
d_f.columns = ['A','B','C','D','E','F'] # change column name
d_f.index = ['a','b','c','d','e','f'] # change index name
d_f

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119
e -0.134841  0.390528  0.166905  0.184502  0.807706  0.072960
f  0.638787  0.329646 -0.497104 -0.754070 -0.943406  0.484752

In [274]:
d_f['A']

a    2.706850
b   -0.848077
c    0.188695
d    2.605967
e   -0.134841
f    0.638787
Name: A, dtype: float64

In [275]:
d_f[['A']]

A
a  2.706850
b -0.848077
c  0.188695
d  2.605967
e -0.134841
f  0.638787

In [276]:
d_f[['A','B']]['b':'d']

A         B
b -0.848077  0.605965
c  0.188695 -0.758872
d  2.605967  0.683509

In [277]:
#d_f['a']

In [278]:
d_f['a':'a']

A         B         C         D         E         F
a  2.70685  0.628133  0.907969  0.503826  0.651118 -0.319318

#loc and iloc

In [279]:
d_f

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119
e -0.134841  0.390528  0.166905  0.184502  0.807706  0.072960
f  0.638787  0.329646 -0.497104 -0.754070 -0.943406  0.484752

In [280]:
d_f.loc['a':'d'] # loc is label based

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119

In [281]:
d_f.iloc[0:4] # iloc is index based

A         B         C         D         E         F
a  2.706850  0.628133  0.907969  0.503826  0.651118 -0.319318
b -0.848077  0.605965 -2.018168  0.740122  0.528813 -0.589001
c  0.188695 -0.758872 -0.933237  0.955057  0.190794  1.978757
d  2.605967  0.683509  0.302665  1.693723 -1.706086 -1.159119

In [282]:
np.random.seed(101)
df2 = pd.DataFrame(np.random.randint(10,50,(7,7)), columns = ['A','B','C','D','E','F','G'],index = ['a','b','c','d','e','f','g'])
df2

A   B   C   D   E   F   G
a  41  21  27  16  33  21  19
b  23  14  38  10  15  22  39
c  29  18  39  44  18  29  20
d  22  41  33  10  19  18  46
e  29  45  38  17  20  49  48
f  19  28  17  49  25  10  22
g  27  21  25  43  39  34  46

In [283]:
df2>20

A      B      C      D      E      F      G
a   True   True   True  False   True   True  False
b   True  False   True  False  False   True   True
c   True  False   True   True  False   True  False
d   True   True   True  False  False  False   True
e   True   True   True  False  False   True   True
f  False   True  False   True   True  False   True
g   True   True   True   True   True   True   True

In [284]:
df2[df2>20]

A     B     C     D     E     F     G
a  41.0  21.0  27.0   NaN  33.0  21.0   NaN
b  23.0   NaN  38.0   NaN   NaN  22.0  39.0
c  29.0   NaN  39.0  44.0   NaN  29.0   NaN
d  22.0  41.0  33.0   NaN   NaN   NaN  46.0
e  29.0  45.0  38.0   NaN   NaN  49.0  48.0
f   NaN  28.0   NaN  49.0  25.0   NaN  22.0
g  27.0  21.0  25.0  43.0  39.0  34.0  46.0

In [285]:
 df2[(df2['A']>20) & (df2['B']>30)]

A   B   C   D   E   F   G
d  22  41  33  10  19  18  46
e  29  45  38  17  20  49  48